/**
 * Populates dist/ with the rendered docs so the npm package is self-contained.
 *
 * Doc source resolution (override with RS_GRID_DOCS_SOURCE=local|github):
 *   1. local  — copy from the sibling repo ../rs-grid-site/doc_build if present
 *               (lets local doc edits reach the MCP without pushing to GitHub)
 *   2. github — download from ruxelion/rs-grid-site@main (the published default)
 * With no override, local is used when the sibling repo exists, else github.
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..", "..");

const DEST_DOC_BUILD = path.join(__dirname, "..", "dist", "doc_build");
const SRC_SKILL = path.join(ROOT, "docs", "skill.md");
const DEST_SKILL = path.join(__dirname, "..", "dist", "skill.md");
const SIBLING_DOC_BUILD = path.resolve(ROOT, "..", "rs-grid-site", "doc_build");

const GITHUB_REPO = "ruxelion/rs-grid-site";
const GITHUB_BRANCH = "main";
const GITHUB_RAW = `https://raw.githubusercontent.com/${GITHUB_REPO}/${GITHUB_BRANCH}`;
const GITHUB_TREE_API = `https://api.github.com/repos/${GITHUB_REPO}/git/trees/${GITHUB_BRANCH}?recursive=1`;

function isDocFile(filePath) {
  const name = path.basename(filePath);
  if (name.endsWith(".md")) return true;
  if (name === "llms.txt" || name === "llms-full.txt") return true;
  return false;
}

// Recursively list doc files under `dir`, returned as paths relative to `dir`.
function walkDocFiles(dir, base = dir) {
  const out = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      out.push(...walkDocFiles(full, base));
    } else if (entry.isFile() && isDocFile(full)) {
      out.push(path.relative(base, full));
    }
  }
  return out;
}

function copyLocalDocs() {
  console.log(`Copying docs from local ${SIBLING_DOC_BUILD}...`);
  const rels = walkDocFiles(SIBLING_DOC_BUILD);
  for (const rel of rels) {
    const dest = path.join(DEST_DOC_BUILD, rel);
    fs.mkdirSync(path.dirname(dest), { recursive: true });
    fs.copyFileSync(path.join(SIBLING_DOC_BUILD, rel), dest);
  }
  return rels.length;
}

async function downloadGithubDocs() {
  console.log(`Fetching doc_build file list from ${GITHUB_REPO}...`);
  const treeRes = await fetch(GITHUB_TREE_API);
  if (!treeRes.ok) {
    console.error(`GitHub API error: ${treeRes.status} ${treeRes.statusText}`);
    process.exit(1);
  }
  const { tree } = await treeRes.json();

  const docFiles = tree.filter(
    (f) =>
      f.type === "blob" &&
      f.path.startsWith("doc_build/") &&
      isDocFile(f.path),
  );

  console.log(`Downloading ${docFiles.length} files...`);
  await Promise.all(
    docFiles.map(async (file) => {
      const url = `${GITHUB_RAW}/${file.path}`;
      const res = await fetch(url);
      if (!res.ok) throw new Error(`Failed to fetch ${url}: ${res.status}`);
      const content = await res.text();
      const dest = path.join(__dirname, "..", "dist", file.path);
      fs.mkdirSync(path.dirname(dest), { recursive: true });
      fs.writeFileSync(dest, content, "utf-8");
    }),
  );
  return docFiles.length;
}

// --- Resolve source and populate dist/doc_build/ ---

// Trim: when set via cmd.exe `set "VAR=github" && ...`, just's quote handling
// can leave a trailing space, which would otherwise fail the equality checks.
const override = process.env.RS_GRID_DOCS_SOURCE?.trim();
const localAvailable = fs.existsSync(SIBLING_DOC_BUILD);

if (override && override !== "local" && override !== "github") {
  console.error(
    `Invalid RS_GRID_DOCS_SOURCE="${override}" (expected "local" or "github").`,
  );
  process.exit(1);
}
if (override === "local" && !localAvailable) {
  console.error(
    `RS_GRID_DOCS_SOURCE=local but no docs found at ${SIBLING_DOC_BUILD}.`,
  );
  process.exit(1);
}

const useLocal = override === "local" || (override !== "github" && localAvailable);

// Clear stale output so switching sources never leaves orphaned pages behind.
fs.rmSync(DEST_DOC_BUILD, { recursive: true, force: true });
fs.mkdirSync(DEST_DOC_BUILD, { recursive: true });

const docCount = useLocal ? copyLocalDocs() : await downloadGithubDocs();

fs.copyFileSync(SRC_SKILL, DEST_SKILL);

// Copy the local scene fixtures (generated by `just gen-scene-fixtures`) so the
// get_scene tool can serve them from the published package.
const SRC_SCENES = path.join(__dirname, "..", "scenes");
const DEST_SCENES = path.join(__dirname, "..", "dist", "scenes");
let sceneCount = 0;
if (fs.existsSync(SRC_SCENES)) {
  fs.mkdirSync(DEST_SCENES, { recursive: true });
  for (const name of fs.readdirSync(SRC_SCENES)) {
    if (name.endsWith(".json")) {
      fs.copyFileSync(
        path.join(SRC_SCENES, name),
        path.join(DEST_SCENES, name),
      );
      sceneCount++;
    }
  }
}

console.log(
  `Done — ${docCount} doc files (${useLocal ? "local" : "github"}) + ` +
    `${sceneCount} scene fixtures into dist/`,
);
