//! Embedded SVG icons: country flags (254) and gender
//! symbols. All icons are base64 data URIs generated at
//! build time. Zero runtime dependencies, zero network
//! requests.
//!
//! ```
//! let uri = rs_grid_icons::flag_data_uri("FR");
//! assert!(uri.is_some());
//! assert!(uri.unwrap().starts_with("data:image/svg+xml"));
//! ```

// Generated by build.rs from flags/*.svg + genders/*.svg.
include!(concat!(env!("OUT_DIR"), "/icons_data.rs"));

// ── Country flags ────────────────────────────────────

/// Return the SVG data URI for a given ISO 3166-1 alpha-2
/// country code (uppercase, e.g. `"FR"`, `"US"`).
pub fn flag_data_uri(code: &str) -> Option<&'static str> {
    FLAGS
        .binary_search_by_key(&code, |(k, _)| k)
        .ok()
        .map(|i| FLAGS[i].1)
}

/// Total number of embedded country flags.
pub fn flag_count() -> usize {
    FLAGS.len()
}

/// Iterator over all `(code, data_uri)` flag pairs.
pub fn all_flags(
) -> impl Iterator<Item = (&'static str, &'static str)> {
    FLAGS.iter().map(|&(k, v)| (k, v))
}

// ── Gender icons ─────────────────────────────────────

/// Return the SVG data URI for a gender icon key
/// (uppercase, e.g. `"MALE"`, `"FEMALE"`).
pub fn gender_icon_uri(
    key: &str,
) -> Option<&'static str> {
    GENDERS
        .binary_search_by_key(&key, |(k, _)| k)
        .ok()
        .map(|i| GENDERS[i].1)
}

/// Total number of embedded gender icons.
pub fn gender_icon_count() -> usize {
    GENDERS.len()
}

/// Iterator over all `(key, data_uri)` gender pairs.
pub fn all_gender_icons(
) -> impl Iterator<Item = (&'static str, &'static str)> {
    GENDERS.iter().map(|&(k, v)| (k, v))
}

#[cfg(test)]
mod tests {
    use super::*;

    // ── flags ────────────────────────────────────

    #[test]
    fn flag_known() {
        assert!(flag_data_uri("FR").is_some());
        assert!(flag_data_uri("US").is_some());
        assert!(flag_data_uri("JP").is_some());
    }

    #[test]
    fn flag_unknown() {
        assert!(flag_data_uri("XX").is_none());
        assert!(flag_data_uri("").is_none());
    }

    #[test]
    fn flag_data_uri_format() {
        let uri = flag_data_uri("FR").unwrap();
        assert!(uri.starts_with(
            "data:image/svg+xml;base64,"
        ));
    }

    #[test]
    fn flag_count_check() {
        assert!(flag_count() >= 250);
    }

    #[test]
    fn flags_sorted() {
        let codes: Vec<&str> =
            FLAGS.iter().map(|(k, _)| *k).collect();
        for w in codes.windows(2) {
            assert!(
                w[0] < w[1],
                "not sorted: {} >= {}",
                w[0],
                w[1]
            );
        }
    }

    // ── genders ──────────────────────────────────

    #[test]
    fn gender_known() {
        assert!(gender_icon_uri("MALE").is_some());
        assert!(gender_icon_uri("FEMALE").is_some());
    }

    #[test]
    fn gender_unknown() {
        assert!(gender_icon_uri("XXX").is_none());
    }

    #[test]
    fn gender_data_uri_format() {
        let uri = gender_icon_uri("MALE").unwrap();
        assert!(uri.starts_with(
            "data:image/svg+xml;base64,"
        ));
    }

    #[test]
    fn gender_count_check() {
        assert_eq!(gender_icon_count(), 2);
    }

    #[test]
    fn genders_sorted() {
        let keys: Vec<&str> =
            GENDERS.iter().map(|(k, _)| *k).collect();
        for w in keys.windows(2) {
            assert!(
                w[0] < w[1],
                "not sorted: {} >= {}",
                w[0],
                w[1]
            );
        }
    }
}
