//! Embedded SVG country flags (254 ISO 3166-1 codes).
//!
//! Flags are embedded as base64 data URIs at build time
//! from the `flags/` directory. Zero runtime dependencies,
//! zero network requests.
//!
//! ```
//! let uri = rs_grid_flags::flag_data_uri("FR");
//! assert!(uri.is_some());
//! assert!(uri.unwrap().starts_with("data:image/svg+xml"));
//! ```

// Generated by build.rs from flags/*.svg.
include!(concat!(env!("OUT_DIR"), "/flags_data.rs"));

/// Return the SVG data URI for a given ISO 3166-1 alpha-2
/// country code (uppercase, e.g. `"FR"`, `"US"`).
///
/// Returns `None` if the code is not recognized.
pub fn flag_data_uri(code: &str) -> Option<&'static str> {
    FLAGS
        .binary_search_by_key(&code, |(k, _)| k)
        .ok()
        .map(|i| FLAGS[i].1)
}

/// Total number of embedded flags.
pub fn flag_count() -> usize {
    FLAGS.len()
}

/// Iterator over all `(code, data_uri)` pairs.
pub fn all_flags(
) -> impl Iterator<Item = (&'static str, &'static str)> {
    FLAGS.iter().map(|&(k, v)| (k, v))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn known_code() {
        assert!(flag_data_uri("FR").is_some());
        assert!(flag_data_uri("US").is_some());
        assert!(flag_data_uri("JP").is_some());
    }

    #[test]
    fn unknown_code() {
        assert!(flag_data_uri("XX").is_none());
        assert!(flag_data_uri("").is_none());
    }

    #[test]
    fn data_uri_format() {
        let uri = flag_data_uri("FR").unwrap();
        assert!(uri.starts_with(
            "data:image/svg+xml;base64,"
        ));
    }

    #[test]
    fn count() {
        assert!(flag_count() >= 250);
    }

    #[test]
    fn sorted() {
        let codes: Vec<&str> =
            FLAGS.iter().map(|(k, _)| *k).collect();
        for w in codes.windows(2) {
            assert!(
                w[0] < w[1],
                "not sorted: {} >= {}",
                w[0],
                w[1]
            );
        }
    }
}
